from src import line, nand, container, printer

c1 = container.Container(2, 2)

n1 = nand.Nand()
n2 = nand.Nand()
n3 = nand.Nand()
n4 = nand.Nand()
n5 = nand.Nand()

l0_0 = line.Line()
l0 = line.Line()

w1 = line.Line(2)
w2 = line.Line(2)
w3 = line.Line(4)
w4 = line.Line()
w5 = line.Line()
w6 = line.Line()
w7 = line.Line()

l0_0.connect_next(c1, 'A', 'A')
l0.connect_next(c1, 'A', 'B')
c1.connect_within(w1, 'A')
c1.connect_within(w2, 'B')
w1.connect_next(n1, 'A', 'A')
w1.connect_next(n4, 'B', 'A')
w2.connect_next(n4, 'A', 'B')
w2.connect_next(n2, 'B', 'B')
n4.connect_next(w3)
w3.connect_next(n1, 'A', 'B')
w3.connect_next(n2, 'B', 'A')
w3.connect_next(n5, 'C', 'A')
w3.connect_next(n5, 'D', 'B')
n1.connect_next(w4)
n2.connect_next(w5)
w4.connect_next(n3, 'A', 'A')
w5.connect_next(n3, 'A', 'B')
n3.connect_next(w6)
n5.connect_next(w7)
w6.connect_next(c1, 'A', 'Z')
w7.connect_next(c1, 'A', 'Y')

p1 = printer.Printer(c1)